name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Yarn install
        shell: bash
        run: |
          yarn install --frozen-lockfile
      ## TODO - Enable after ts, lint, and test are fixed
      # - name: Validate
      #   run: |
      #     yarn nx run datalab-excel:ts
      #     yarn nx run datalab-excel:lint
      #     yarn nx run datalab-excel:test
      - name: Build
        run: |
          NX_GRAPHQL_URL=https://ghexcel.int.oncmg.io/dlgw/graphql yarn nx run datalab-excel:build
      ## TODO - Manifest files must have the fully qualified host location baked in. Dynamically generate and add to build output before deployment.
      # - name: Generate Preview Environment Manifest
      #   if: github.event_name == 'pull_request'
      #   run: |
      #     yarn nx run datalab-excel:generate-manifest https://witty-island-0ef27c110-${{ github.event.pull_request.number }}.centralus.4.azurestaticapps.net
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_ISLAND_0EF27C110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          skip_app_build: true # https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#skip-building-front-end-app
          app_location: '/dist/apps/datalab-excel' # App source code path - it's the built version when `skip_app_build: true`
          output_location: ''
          ###### End of Repository/Build Configurations ######
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_ISLAND_0EF27C110 }}
          action: 'close'
